class ForeWrap:
    @property
    def BLACK(self): ...
    @property
    def RED(self): ...
    @property
    def GREEN(self): ...
    @property
    def YELLOW(self): ...
    @property
    def BLUE(self): ...
    @property
    def MAGENTA(self): ...
    @property
    def CYAN(self): ...
    @property
    def WHITE(self): ...
    @property
    def RESET(self): ...
    @property
    def LIGHTBLACK_EX(self): ...
    @property
    def LIGHTRED_EX(self): ...
    @property
    def LIGHTGREEN_EX(self): ...
    @property
    def LIGHTYELLOW_EX(self): ...
    @property
    def LIGHTBLUE_EX(self): ...
    @property
    def LIGHTMAGENTA_EX(self): ...
    @property
    def LIGHTCYAN_EX(self): ...
    @property
    def LIGHTWHITE_EX(self): ...

class BackWrap:
    @property
    def BLACK(self): ...
    @property
    def RED(self): ...
    @property
    def GREEN(self): ...
    @property
    def YELLOW(self): ...
    @property
    def BLUE(self): ...
    @property
    def MAGENTA(self): ...
    @property
    def CYAN(self): ...
    @property
    def WHITE(self): ...
    @property
    def RESET(self): ...
    @property
    def LIGHTBLACK_EX(self): ...
    @property
    def LIGHTRED_EX(self): ...
    @property
    def LIGHTGREEN_EX(self): ...
    @property
    def LIGHTYELLOW_EX(self): ...
    @property
    def LIGHTBLUE_EX(self): ...
    @property
    def LIGHTMAGENTA_EX(self): ...
    @property
    def LIGHTCYAN_EX(self): ...
    @property
    def LIGHTWHITE_EX(self): ...

Fore: ForeWrap = ...
Back: BackWrap = ...
