/* Generated by Cython 0.29.23 */

#ifndef __PYX_HAVE__rubbish__core__command
#define __PYX_HAVE__rubbish__core__command

#include "Python.h"
struct word_list;
union redirector;
struct redirect;
struct element;
union command_info;
struct command;
struct connection;
struct simple_cm;

/* "rubbish/core/command.pxd":1
 * cpdef public enum CommandType "command_type":             # <<<<<<<<<<<<<<
 *     cm_simple
 *     cm_connection
 */
enum command_type {
  cm_simple,
  cm_connection
};

/* "rubbish/core/command.pxd":5
 *     cm_connection
 * 
 * cpdef public enum RedirectInstruction "redirect_instruction":             # <<<<<<<<<<<<<<
 *     r_output_direction
 *     r_input_direction
 */
enum redirect_instruction {
  r_output_direction,
  r_input_direction,
  r_appending_to
};

/* "rubbish/core/command.pxd":10
 *     r_appending_to
 * 
 * cdef public struct word_list:             # <<<<<<<<<<<<<<
 *     word_list *next
 *     char *word
 */
struct word_list {
  struct word_list *next;
  char *word;
};

/* "rubbish/core/command.pxd":14
 *     char *word
 * 
 * ctypedef public word_list WORD_LIST             # <<<<<<<<<<<<<<
 * 
 * cdef public union redirector:
 */
typedef struct word_list WORD_LIST;

/* "rubbish/core/command.pxd":16
 * ctypedef public word_list WORD_LIST
 * 
 * cdef public union redirector:             # <<<<<<<<<<<<<<
 *     int dest
 *     char *filename
 */
union redirector {
  int dest;
  char *filename;
};

/* "rubbish/core/command.pxd":20
 *     char *filename
 * 
 * ctypedef public redirector REDIRECTOR             # <<<<<<<<<<<<<<
 * 
 * cdef public struct redirect:
 */
typedef union redirector REDIRECTOR;

/* "rubbish/core/command.pxd":22
 * ctypedef public redirector REDIRECTOR
 * 
 * cdef public struct redirect:             # <<<<<<<<<<<<<<
 *     redirect *next
 *     REDIRECTOR redirector
 */
struct redirect {
  struct redirect *next;
  REDIRECTOR redirector;
  enum redirect_instruction instruction;
  REDIRECTOR redirectee;
};

/* "rubbish/core/command.pxd":28
 *     REDIRECTOR redirectee
 * 
 * ctypedef public redirect REDIRECT             # <<<<<<<<<<<<<<
 * 
 * cdef public struct element:
 */
typedef struct redirect REDIRECT;

/* "rubbish/core/command.pxd":30
 * ctypedef public redirect REDIRECT
 * 
 * cdef public struct element:             # <<<<<<<<<<<<<<
 *   char *word
 *   REDIRECT *redirect
 */
struct element {
  char *word;
  REDIRECT *redirect;
};

/* "rubbish/core/command.pxd":33
 *   char *word
 *   REDIRECT *redirect
 * ctypedef public element ELEMENT             # <<<<<<<<<<<<<<
 * 
 * cdef public union command_info:
 */
typedef struct element ELEMENT;

/* "rubbish/core/command.pxd":35
 * ctypedef public element ELEMENT
 * 
 * cdef public union command_info:             # <<<<<<<<<<<<<<
 *     connection *Connection
 *     simple_cm *Simple
 */
union command_info {
  struct connection *Connection;
  struct simple_cm *Simple;
};

/* "rubbish/core/command.pxd":39
 *     simple_cm *Simple
 * 
 * ctypedef public command_info COMMAND_INFO             # <<<<<<<<<<<<<<
 * 
 * cdef public struct command:
 */
typedef union command_info COMMAND_INFO;

/* "rubbish/core/command.pxd":41
 * ctypedef public command_info COMMAND_INFO
 * 
 * cdef public struct command:             # <<<<<<<<<<<<<<
 *     CommandType type
 *     command_info info
 */
struct command {
  enum command_type type;
  union command_info info;
};

/* "rubbish/core/command.pxd":45
 *     command_info info
 * 
 * ctypedef public command COMMAND             # <<<<<<<<<<<<<<
 * 
 * cdef public struct connection:
 */
typedef struct command COMMAND;

/* "rubbish/core/command.pxd":47
 * ctypedef public command COMMAND
 * 
 * cdef public struct connection:             # <<<<<<<<<<<<<<
 *     COMMAND *first
 *     COMMAND *second
 */
struct connection {
  COMMAND *first;
  COMMAND *second;
  int connector;
};

/* "rubbish/core/command.pxd":52
 *     int connector
 * 
 * ctypedef public connection CONNECTION             # <<<<<<<<<<<<<<
 * 
 * cdef public struct simple_cm:
 */
typedef struct connection CONNECTION;

/* "rubbish/core/command.pxd":54
 * ctypedef public connection CONNECTION
 * 
 * cdef public struct simple_cm:             # <<<<<<<<<<<<<<
 *     WORD_LIST *words
 *     REDIRECT *redirects
 */
struct simple_cm {
  WORD_LIST *words;
  REDIRECT *redirects;
};

/* "rubbish/core/command.pxd":58
 *     REDIRECT *redirects
 * 
 * ctypedef public simple_cm SIMPLE_COMMAND             # <<<<<<<<<<<<<<
 * 
 * cdef class Redirect:
 */
typedef struct simple_cm SIMPLE_COMMAND;

#ifndef __PYX_HAVE_API__rubbish__core__command

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__rubbish__core__command */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcommand(void);
#else
PyMODINIT_FUNC PyInit_command(void);
#endif

#endif /* !__PYX_HAVE__rubbish__core__command */
