from typing import Optional

class Config:
    def __init__(self, file: str = ..., use_ansi: bool = ...): ...
    @property
    def file(self) -> Optional[str]: ...
    @file.setter
    def file(self, value: str) -> None: ...
    @property
    def interactive(self) -> bool: ...
    @property
    def use_ansi(self) -> bool: ...
    @use_ansi.setter
    def use_ansi(self, value: bool) -> None: ...

def set_config(config: Config) -> None: ...
def get_config() -> Config: ...
