class Config:
    def __init__(self, interactive: bool = False, use_ansi: bool = ...): ...
    @property
    def interactive(self) -> bool: ...
    @interactive.setter
    def interactive(self, value: bool) -> None: ...
    @property
    def use_ansi(self) -> bool: ...
    @use_ansi.setter
    def use_ansi(self, value: bool) -> None: ...

def set_config(config: Config): ...
def get_config() -> Config: ...
