class Config:
    def __init__(self, use_ansi: bool = ...): ...
    @property
    def use_ansi(self) -> bool: ...
    @use_ansi.setter
    def use_ansi(self, value: bool): ...

def set_config(config: Config) -> None: ...
def get_config() -> Config: ...
