from .command import Command, SimpleCommand, Connection

def execute_command(command: Command, input: int, output: int, async: bool): ...
def execute_simplecommand(
    command: SimpleCommand, input: int, output: int, async: bool
): ...
def execute_connection(command: Connection, input: int, output: int, async: bool): ...
def cd(dir: str): ...
