from typing import Tuple, NoReturn, Optional

from .command import Command, SimpleCommand, Connection

def execute_command(
    command: Command, input: int, output: int, async: bool = False
) -> int: ...
def execute_simplecommand(command: SimpleCommand, input: int, output: int) -> int: ...
def execute_connection(command: Connection, input: int, output: int) -> int: ...
def cd(dir: Optional[str] = None) -> int: ...
def exit() -> NoReturn: ...
def alias(
    output: int, name: Optional[str] = None, words: Tuple[str, ...] = tuple()
) -> int: ...
def unalias(name: str) -> int: ...
def export(
    output: int, name: Optional[str] = None, value: Optional[str] = None
) -> int: ...
def help() -> int: ...
