from typing import List

from .command import Command

def parse(input: str, interactive: bool = ...) -> List[Command]: ...
def parse_file(filename: str) -> List[Command]: ...

class MoreInputNeeded(Exception): ...
